# Model arguments
model_name_or_path: /mnt/data-rundong/phi-3
model_revision: main
torch_dtype: float16
use_flash_attention_2: false

# Data training arguments
preprocessing_num_workers: 12
data_root: /mnt/data-rundong/bridge2_processed/tokenized/
padding_side: left
num_visual_action_tokens: 16384
static_video_description:
  - ""
dataset_type: dataset # or iterable_dataset
data_debug: true

# SFT trainer config
deepspeed: configs/deepspeed/ds_zero2.json
bf16: false
fp16: true
do_eval: true
evaluation_strategy: steps
eval_steps: 500
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_strategy: steps
logging_steps: 5  
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: 25000
output_dir: ./experimetns/phi-3-debug
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: steps
save_steps: 1000
save_total_limit: 10
load_best_model_at_end: true
seed: 42
warmup_ratio: 0.1
save_on_each_node: false