# Model arguments
model_name_or_path: /mnt/data-rundong/mistral-7B-v0.1
model_revision: main
torch_dtype: float16
use_flash_attention_2: false
disable_auto_config: true
model_type: mistral
va_ncodes: 16384
va_embedding_dim: 256
va_checkpoint: /mnt/data-rundong/VQ3D-vision-action/0929-ftpizza-4ldec-bs128-open0close1-lr1e-6-width07-continue-0725-step95000/checkpoints/step_checkpoint-step_50000.ckpt
v_mask_ratio: 0.0

# Data training arguments
preprocessing_num_workers: 12
# data_root: /mnt/data-rundong/robot_datasets/0531-action111-bridge-noMask-woResidual_tokenized_stacked/
data_roots:
  - /mnt/data-rundong/robot_datasets/0929-ftpizza-4ldec-bs128-open0close1-lr1e-6-width07-continue-0725-step95000_step50000_tokenized_stacked_v2/pizza_width/
  # - /mnt/data-rundong/robot_datasets/0725-dinov2-action111-bridgeRT-noMask-woResidual-usePixelWeight-continueTrain0722_step95000_tokenized_stacked/bridge2/
  # - /mnt/data-rundong/robot_datasets/0725-dinov2-action111-bridgeRT-noMask-woResidual-usePixelWeight-continueTrain0722_step95000_tokenized_stacked/rt1/
padding_side: left
num_visual_action_tokens: 16384
static_video_description:
  - ""
dataset_type: dataset # or iterable_dataset
action_before_vision: false
wo_vision: true

# SFT trainer config
deepspeed: configs/deepspeed/ds_zero3.json
bf16: false
fp16: true
do_eval: true
eval_strategy: steps
eval_steps: 1000
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
log_level: info
logging_strategy: steps
logging_steps: 5  
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: 50000
output_dir: /mnt/data-rundong/VLA-experiments/1018-FTpizza-woVision-width07-vq-4ldec-dropout01-0929-step50000-continue0812-step24000/
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
remove_unused_columns: true
report_to:
- tensorboard
save_strategy: steps
save_steps: 2000
save_total_limit: 10
load_best_model_at_end: true
seed: 42
warmup_ratio: 0.0
save_on_each_node: false
resume_from_checkpoint: /mnt/data-rundong/VLA-experiments/0812-tokenize0722-step_95000-bridgeRT-VisionFirst-vaFeat-noMask-mistral-piece2of2/checkpoint-24000/
# resume_from_checkpoint: /mnt/data-rundong/VLA-experiments/1015-FTpizza-width07-vq-3ldec-1012-step8000-continue0812-step24000-visionFirst/checkpoint-7500/